# Generated by Django 4.2 on 2025-02-14 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marblecontacts', '0003_alter_contactmarble_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmarble',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactmarble',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='contactmarble',
            name='state',
        ),
    ]
