# Generated by Django 4.2 on 2025-02-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilecontacts', '0003_alter_contacttile_id_alter_contacttile_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacttile',
            name='state',
            field=models.TextField(blank=True),
        ),
    ]
