# Generated by Django 4.2 on 2025-02-13 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tilecontacts', '0004_alter_contacttile_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacttile',
            name='state',
        ),
    ]
