# Generated by Django 4.2 on 2025-02-13 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tilecontacts', '0005_remove_contacttile_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacttile',
            name='last_name',
        ),
    ]
